quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/identity_service
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}

quarkus.otel.enabled=false
quarkus.otel.exporter.otlp.endpoint=http://localhost:4317

quarkus.http.proxy.proxy-address-forwarding=true
quarkus.http.proxy.allow-x-forwarded=true
quarkus.http.proxy.enable-forwarded-host=true
quarkus.http.proxy.enable-forwarded-prefix=true
quarkus.http.proxy.trusted-proxies=nginx

quarkus.swagger-ui.always-include=true

quarkus.rabbitmqclient.virtual-host=/
quarkus.rabbitmqclient.username=${RABBITMQ_USER}
quarkus.rabbitmqclient.password=${RABBITMQ_PASS}
quarkus.rabbitmqclient.hostname=rabbitmq
quarkus.rabbitmqclient.port=5672