quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/test
quarkus.datasource.username=postgres
quarkus.datasource.password=123456

quarkus.hibernate-orm.schema-management.strategy=update

quarkus.rest.exception-mapping.disable-mapper-for=io.quarkus.resteasy.reactive.jackson.runtime.mappers.BuiltinMismatchedInputExceptionMapper
quarkus.log.category."org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext".level=DEBUG

quarkus.mailer.from=Minion Flow <noreply@ripoonchig.me>

quarkus.mailer.host=smtp.resend.com
quarkus.mailer.port=587
quarkus.mailer.username=resend

quarkus.mailer.tls=false
quarkus.mailer.start-tls=REQUIRED

quarkus.mailer.mock=false