quarkus.application.name=identity-service

quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.hibernate-orm.schema-management.strategy=validate

quarkus.smallrye-openapi.security-scheme=jwt
quarkus.smallrye-openapi.security-scheme-name=BearerAuth
quarkus.smallrye-openapi.security-scheme-description=JWT Bearer token
quarkus.smallrye-openapi.jwt-security-scheme-value=bearer
quarkus.smallrye-openapi.jwt-bearer-format=JWT
quarkus.smallrye-openapi.auto-add-security-requirement=true
quarkus.swagger-ui.persist-authorization=true
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem

quarkus.rest.exception-mapping.disable-mapper-for=io.quarkus.resteasy.reactive.jackson.runtime.mappers.BuiltinMismatchedInputExceptionMapper
#quarkus.log.category."org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext".level=DEBUG

quarkus.mailer.from=Minion Flow <noreply@ripoonchig.me>
quarkus.mailer.host=smtp.resend.com
quarkus.mailer.port=587
quarkus.mailer.username=resend
quarkus.mailer.tls=false
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.mock=false

quarkus.rabbitmqclient.connection-recovery=true
quarkus.rabbitmqclient.topology-recovery=true
quarkus.rabbitmqclient.network-recovery-interval=5000
quarkus.rabbitmqclient.requested-heartbeat=30
quarkus.rabbitmqclient.metrics.enabled=false
