quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/artifact_service
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}

quarkus.otel.enabled=false
quarkus.otel.exporter.otlp.endpoint=http://localhost:4317

quarkus.s3.path-style-access=true
quarkus.s3.endpoint-override=http://minio:9000
quarkus.s3.aws.region=ru-central1
quarkus.s3.aws.credentials.type=static
quarkus.s3.aws.credentials.static-provider.access-key-id=${MINIO_ROOT_USER}
quarkus.s3.aws.credentials.static-provider.secret-access-key=${MINIO_ROOT_PASSWORD}
quarkus.http.limits.max-body-size=200M

quarkus.http.proxy.proxy-address-forwarding=true
quarkus.http.proxy.allow-x-forwarded=true
quarkus.http.proxy.enable-forwarded-host=true
quarkus.http.proxy.enable-forwarded-prefix=true
quarkus.http.proxy.trusted-proxies=nginx

quarkus.swagger-ui.always-include=true

quarkus.rabbitmqclient.virtual-host=/
quarkus.rabbitmqclient.username=${RABBITMQ_USER}
quarkus.rabbitmqclient.password=${RABBITMQ_PASS}
quarkus.rabbitmqclient.hostname=rabbitmq
quarkus.rabbitmqclient.port=5672

quarkus.rest-client.engine-api.url=http://engine-api:8080
quarkus.rest-client.engine-log.url=http://execution-logs:8080