quarkus.application.name=artifact-service
quarkus.http.port=8082

quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.hibernate-orm.mapping.format.global=ignore

quarkus.smallrye-openapi.security-scheme=jwt
quarkus.smallrye-openapi.security-scheme-name=BearerAuth
quarkus.smallrye-openapi.security-scheme-description=JWT Bearer token
quarkus.smallrye-openapi.jwt-security-scheme-value=bearer
quarkus.smallrye-openapi.jwt-bearer-format=JWT
quarkus.smallrye-openapi.auto-add-security-requirement=true
quarkus.swagger-ui.persist-authorization=true
mp.jwt.verify.publickey.location=publicKey.pem

quarkus.rest.exception-mapping.disable-mapper-for=io.quarkus.resteasy.reactive.jackson.runtime.mappers.BuiltinMismatchedInputExceptionMapper
#quarkus.log.category."org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext".level=DEBUG

quarkus.rabbitmqclient.connection-recovery=true
quarkus.rabbitmqclient.topology-recovery=true
quarkus.rabbitmqclient.network-recovery-interval=5000
quarkus.rabbitmqclient.requested-heartbeat=30
quarkus.rabbitmqclient.metrics.enabled=false

quarkus.rest-client.engine-api.connect-timeout=2000
quarkus.rest-client.engine-api.read-timeout=5000

quarkus.rest-client.engine-log.connect-timeout=2000
quarkus.rest-client.engine-log.read-timeout=5000

quarkus.websockets-next.server.supported-subprotocols=bearer-token-carrier
quarkus.websockets-next.server.propagate-subprotocol-headers=true