CREATE SEQUENCE IF NOT EXISTS project_members_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE inbox_messages
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message_id         VARCHAR(255)                            NOT NULL,
    status             VARCHAR(255)                            NOT NULL,
    fail_reason        VARCHAR(255),
    attempts_remaining INTEGER                                 NOT NULL,
    CONSTRAINT pk_inbox_messages PRIMARY KEY (id)
);

CREATE TABLE outbox_messages
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message_id         VARCHAR(255)                            NOT NULL,
    queue              VARCHAR(255)                            NOT NULL,
    status             VARCHAR(255)                            NOT NULL,
    content            TEXT                                    NOT NULL,
    fail_reason        VARCHAR(255),
    leased_by          INTEGER                                 NOT NULL,
    leased_until       TIMESTAMP WITH TIME ZONE,
    attempts_remaining INTEGER                                 NOT NULL,
    next_attempt_at    TIMESTAMP WITH TIME ZONE,
    created_at         TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_outbox_messages PRIMARY KEY (id)
);

CREATE TABLE project_members
(
    id          BIGINT                      NOT NULL,
    project_id  UUID                        NOT NULL,
    user_id     UUID                        NOT NULL,
    role        VARCHAR(255)                NOT NULL,
    memberSince TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_project_members PRIMARY KEY (id)
);

CREATE TABLE projects
(
    id                 UUID                        NOT NULL,
    projectName        VARCHAR(255)                NOT NULL,
    projectDescription VARCHAR(255)                NOT NULL,
    createdAt          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

CREATE TABLE remote_users
(
    user_id  UUID         NOT NULL,
    username VARCHAR(255) NOT NULL,
    CONSTRAINT pk_remote_users PRIMARY KEY (user_id)
);

ALTER TABLE project_members
    ADD CONSTRAINT projectmembers_project_user_uniq UNIQUE (project_id, user_id);

ALTER TABLE inbox_messages
    ADD CONSTRAINT uc_inbox_messages_message UNIQUE (message_id);

ALTER TABLE outbox_messages
    ADD CONSTRAINT uc_outbox_messages_message UNIQUE (message_id);

ALTER TABLE project_members
    ADD CONSTRAINT FK_PROJECT_MEMBERS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;

ALTER TABLE project_members
    ADD CONSTRAINT FK_PROJECT_MEMBERS_ON_USER FOREIGN KEY (user_id) REFERENCES remote_users (user_id);