CREATE TABLE inbox_messages
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    messageId         VARCHAR(255)                            NOT NULL,
    status            VARCHAR(255)                            NOT NULL,
    failReason        VARCHAR(255),
    attemptsRemaining INTEGER                                 NOT NULL,
    CONSTRAINT pk_inbox_messages PRIMARY KEY (id)
);

CREATE TABLE outbox_messages
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    messageId         VARCHAR(255)                            NOT NULL,
    queue             VARCHAR(255)                            NOT NULL,
    status            VARCHAR(255)                            NOT NULL,
    content           VARCHAR(255)                            NOT NULL,
    failReason        VARCHAR(255),
    leasedBy          INTEGER                                 NOT NULL,
    leasedUntil       TIMESTAMP WITHOUT TIME ZONE,
    attemptsRemaining INTEGER                                 NOT NULL,
    nextAttemptAt     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_outbox_messages PRIMARY KEY (id)
);

ALTER TABLE inbox_messages
    ADD CONSTRAINT uc_inbox_messages_messageid UNIQUE (messageId);

ALTER TABLE outbox_messages
    ADD CONSTRAINT uc_outbox_messages_messageid UNIQUE (messageId);