apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  publicKey.pem: |
    -----BEGIN PUBLIC KEY-----
    insert here
    -----END PUBLIC KEY-----
  privateKey.pem: |
    -----BEGIN PRIVATE KEY-----
        insert here
    -----END PRIVATE KEY-----
