CREATE SEQUENCE IF NOT EXISTS email_messages_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS verification_tickets_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE email_messages
(
    id          BIGINT                   NOT NULL,
    email       VARCHAR(255)             NOT NULL,
    subject     TEXT                     NOT NULL,
    content     TEXT                     NOT NULL,
    is_sent     BOOLEAN                  NOT NULL,
    is_failed   BOOLEAN                  NOT NULL,
    fail_reason VARCHAR(255),
    taken_by    INTEGER                  NOT NULL,
    taken_until TIMESTAMP WITH TIME ZONE NOT NULL,
    attempts    INTEGER                  NOT NULL,
    next_try_in TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_email_messages PRIMARY KEY (id)
);

CREATE TABLE inbox_messages
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message_id         VARCHAR(255)                            NOT NULL,
    status             VARCHAR(255)                            NOT NULL,
    fail_reason        VARCHAR(255),
    attempts_remaining INTEGER                                 NOT NULL,
    CONSTRAINT pk_inbox_messages PRIMARY KEY (id)
);

CREATE TABLE outbox_messages
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message_id         VARCHAR(255)                            NOT NULL,
    queue              VARCHAR(255)                            NOT NULL,
    status             VARCHAR(255)                            NOT NULL,
    content            TEXT                                    NOT NULL,
    fail_reason        VARCHAR(255),
    leased_by          INTEGER                                 NOT NULL,
    leased_until       TIMESTAMP WITH TIME ZONE,
    attempts_remaining INTEGER                                 NOT NULL,
    next_attempt_at    TIMESTAMP WITH TIME ZONE,
    created_at         TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_outbox_messages PRIMARY KEY (id)
);

CREATE TABLE user_sessions
(
    session_id UUID NOT NULL,
    jwt_id     UUID NOT NULL,
    user_id    UUID NOT NULL,
    CONSTRAINT pk_user_sessions PRIMARY KEY (session_id)
);

CREATE TABLE users
(
    user_id       UUID         NOT NULL,
    email         VARCHAR(255) NOT NULL,
    username      VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    status        VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE verification_tickets
(
    id                 BIGINT                   NOT NULL,
    user_id            UUID                     NOT NULL,
    type               VARCHAR(255)             NOT NULL,
    verification_token UUID                     NOT NULL,
    valid_from         TIMESTAMP WITH TIME ZONE NOT NULL,
    valid_to           TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_verification_tickets PRIMARY KEY (id)
);

ALTER TABLE inbox_messages
    ADD CONSTRAINT uc_inbox_messages_message UNIQUE (message_id);

ALTER TABLE outbox_messages
    ADD CONSTRAINT uc_outbox_messages_message UNIQUE (message_id);

ALTER TABLE user_sessions
    ADD CONSTRAINT uc_user_sessions_jwt UNIQUE (jwt_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE user_sessions
    ADD CONSTRAINT FK_USER_SESSIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE;

ALTER TABLE verification_tickets
    ADD CONSTRAINT FK_VERIFICATION_TICKETS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE;