apiVersion: v1
kind: Service
metadata:
  name: artifact-service
spec:
  type: ClusterIP
  selector:
    app: artifact-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifact-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifact-service
  template:
    metadata:
      labels:
        app: artifact-service
    spec:
      containers:
        - name: artifact-service
          image: minionflow-artifact-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: QUARKUS_PROFILE
              value: prod
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: password
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: access_key
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secret_key
            - name: MP_JWT_VERIFY_PUBLICKEY_LOCATION
              value: /etc/minionflow/jwt/publicKey.pem
            - name: QUARKUS_REST_CLIENT_ENGINE_API_URL
              value: http://engine-api:8080
            - name: QUARKUS_REST_CLIENT_ENGINE_LOG_URL
              value: http://execution-logs:8080
          volumeMounts:
            - name: jwt
              mountPath: /etc/minionflow/jwt
              readOnly: true
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
      volumes:
        - name: jwt
          secret:
            secretName: jwt-secret
            items:
              - key: publicKey.pem
                path: publicKey.pem
