apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: ClusterIP
  selector:
    app: identity-service
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          image: minionflow-identity-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_PROFILE
              value: prod
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: password
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
            - name: QUARKUS_MAILER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail-secret
                  key: password
            - name: SMALLRYE_JWT_SIGN_KEY_LOCATION
              value: /etc/minionflow/jwt/privateKey.pem
            - name: MP_JWT_VERIFY_PUBLICKEY_LOCATION
              value: /etc/minionflow/jwt/publicKey.pem
          volumeMounts:
            - name: jwt
              mountPath: /etc/minionflow/jwt
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: jwt
          secret:
            secretName: jwt-secret
            items:
              - key: privateKey.pem
                path: privateKey.pem
              - key: publicKey.pem
                path: publicKey.pem
