CREATE TABLE artifacts
(
    id                    UUID                        NOT NULL,
    projectId             UUID                        NOT NULL,
    userId                UUID                        NOT NULL,
    size                  BIGINT                      NOT NULL,
    originalName          VARCHAR(255)                NOT NULL,
    contentType           VARCHAR(255)                NOT NULL,
    createdAt             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    type                  VARCHAR(255)                NOT NULL,
    storage_identifier_id BIGINT                      NOT NULL,
    CONSTRAINT pk_artifacts PRIMARY KEY (id)
);

CREATE TABLE execution_configs
(
    id        UUID                        NOT NULL,
    alias     VARCHAR(255)                NOT NULL,
    projectId UUID                        NOT NULL,
    userId    UUID                        NOT NULL,
    createdAt TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    content   JSONB                       NOT NULL,
    CONSTRAINT pk_execution_configs PRIMARY KEY (id)
);

CREATE TABLE input_artifacts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    artifact_id UUID                                    NOT NULL,
    alias       VARCHAR(255)                            NOT NULL,
    type        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_input_artifacts PRIMARY KEY (id)
);

CREATE TABLE jar_artifacts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    artifact_id UUID                                    NOT NULL,
    alias       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_jar_artifacts PRIMARY KEY (id)
);

CREATE TABLE storage_identifiers
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    storageKey VARCHAR(255)                            NOT NULL,
    usedIn     INTEGER                                 NOT NULL,
    wasDeleted BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_storage_identifiers PRIMARY KEY (id)
);

CREATE TABLE "task-run_artifact"
(
    output_id UUID NOT NULL,
    task_id   UUID NOT NULL,
    CONSTRAINT "pk_task-run_artifact" PRIMARY KEY (output_id, task_id)
);

CREATE TABLE task_runs
(
    id                  UUID                        NOT NULL,
    projectId           UUID                        NOT NULL,
    userId              UUID                        NOT NULL,
    status              VARCHAR(255)                NOT NULL,
    jar_artifact_id     BIGINT,
    input_artifact_id   BIGINT,
    jar_jpa_id          BIGINT,
    input_jpa_id        BIGINT,
    execution_config_id UUID,
    createdAt           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    startedAt           TIMESTAMP WITHOUT TIME ZONE,
    finishedAt          TIMESTAMP WITHOUT TIME ZONE,
    doneAt              TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_task_runs PRIMARY KEY (id)
);

ALTER TABLE input_artifacts
    ADD CONSTRAINT uc_input_artifacts_artifact UNIQUE (artifact_id);

ALTER TABLE jar_artifacts
    ADD CONSTRAINT uc_jar_artifacts_artifact UNIQUE (artifact_id);

ALTER TABLE storage_identifiers
    ADD CONSTRAINT uc_storage_identifiers_storagekey UNIQUE (storageKey);

ALTER TABLE artifacts
    ADD CONSTRAINT FK_ARTIFACTS_ON_STORAGE_IDENTIFIER FOREIGN KEY (storage_identifier_id) REFERENCES storage_identifiers (id) ON DELETE RESTRICT;

ALTER TABLE input_artifacts
    ADD CONSTRAINT FK_INPUT_ARTIFACTS_ON_ARTIFACT FOREIGN KEY (artifact_id) REFERENCES artifacts (id) ON DELETE CASCADE;

ALTER TABLE jar_artifacts
    ADD CONSTRAINT FK_JAR_ARTIFACTS_ON_ARTIFACT FOREIGN KEY (artifact_id) REFERENCES artifacts (id) ON DELETE CASCADE;

ALTER TABLE task_runs
    ADD CONSTRAINT FK_TASK_RUNS_ON_EXECUTION_CONFIG FOREIGN KEY (execution_config_id) REFERENCES execution_configs (id) ON DELETE SET NULL;

ALTER TABLE task_runs
    ADD CONSTRAINT FK_TASK_RUNS_ON_INPUT_ARTIFACT FOREIGN KEY (input_artifact_id) REFERENCES storage_identifiers (id) ON DELETE SET NULL;

ALTER TABLE task_runs
    ADD CONSTRAINT FK_TASK_RUNS_ON_INPUT_JPA FOREIGN KEY (input_jpa_id) REFERENCES input_artifacts (id) ON DELETE SET NULL;

ALTER TABLE task_runs
    ADD CONSTRAINT FK_TASK_RUNS_ON_JAR_ARTIFACT FOREIGN KEY (jar_artifact_id) REFERENCES storage_identifiers (id) ON DELETE SET NULL;

ALTER TABLE task_runs
    ADD CONSTRAINT FK_TASK_RUNS_ON_JAR_JPA FOREIGN KEY (jar_jpa_id) REFERENCES jar_artifacts (id) ON DELETE SET NULL;

ALTER TABLE "task-run_artifact"
    ADD CONSTRAINT fk_tasart_on_artifact FOREIGN KEY (output_id) REFERENCES artifacts (id);

ALTER TABLE "task-run_artifact"
    ADD CONSTRAINT fk_tasart_on_task_run FOREIGN KEY (task_id) REFERENCES task_runs (id);