CREATE TABLE artifacts
(
    id                    UUID         NOT NULL,
    projectId             UUID         NOT NULL,
    userId                UUID         NOT NULL,
    size                  BIGINT       NOT NULL,
    alias                 VARCHAR(255) NOT NULL,
    originalName          VARCHAR(255) NOT NULL,
    contentType           VARCHAR(255) NOT NULL,
    createdAt             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    type                  VARCHAR(255) NOT NULL,
    storage_identifier_id BIGINT       NOT NULL,
    CONSTRAINT pk_artifacts PRIMARY KEY (id)
);

CREATE TABLE input_artifacts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    artifact_id UUID                                    NOT NULL,
    type        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_input_artifacts PRIMARY KEY (id)
);

CREATE TABLE storage_identifiers
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    storageKey VARCHAR(255)                            NOT NULL,
    usedIn     INTEGER                                 NOT NULL,
    CONSTRAINT pk_storage_identifiers PRIMARY KEY (id)
);

ALTER TABLE input_artifacts
    ADD CONSTRAINT uc_input_artifacts_artifact UNIQUE (artifact_id);

ALTER TABLE storage_identifiers
    ADD CONSTRAINT uc_storage_identifiers_storagekey UNIQUE (storageKey);

ALTER TABLE artifacts
    ADD CONSTRAINT FK_ARTIFACTS_ON_STORAGE_IDENTIFIER FOREIGN KEY (storage_identifier_id) REFERENCES storage_identifiers (id) ON DELETE RESTRICT;

ALTER TABLE input_artifacts
    ADD CONSTRAINT FK_INPUT_ARTIFACTS_ON_ARTIFACT FOREIGN KEY (artifact_id) REFERENCES artifacts (id) ON DELETE CASCADE;