CREATE TABLE artifacts
(
    id                    UUID                     NOT NULL,
    project_id            UUID                     NOT NULL,
    user_id               UUID                     NOT NULL,
    size                  BIGINT                   NOT NULL,
    original_name         VARCHAR(255)             NOT NULL,
    content_type          VARCHAR(255)             NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    type                  VARCHAR(255)             NOT NULL,
    storage_identifier_id BIGINT                   NOT NULL,
    CONSTRAINT pk_artifacts PRIMARY KEY (id)
);

CREATE TABLE execution_configs
(
    id         UUID                     NOT NULL,
    alias      VARCHAR(255)             NOT NULL,
    project_id UUID                     NOT NULL,
    user_id    UUID                     NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    content    JSONB                    NOT NULL,
    CONSTRAINT pk_execution_configs PRIMARY KEY (id)
);

CREATE TABLE inbox_messages
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message_id         VARCHAR(255)                            NOT NULL,
    status             VARCHAR(255)                            NOT NULL,
    fail_reason        VARCHAR(255),
    attempts_remaining INTEGER                                 NOT NULL,
    CONSTRAINT pk_inbox_messages PRIMARY KEY (id)
);

CREATE TABLE input_artifacts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    artifact_id UUID                                    NOT NULL,
    alias       VARCHAR(255)                            NOT NULL,
    type        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_input_artifacts PRIMARY KEY (id)
);

CREATE TABLE jar_artifacts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    artifact_id UUID                                    NOT NULL,
    alias       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_jar_artifacts PRIMARY KEY (id)
);

CREATE TABLE outbox_messages
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message_id         VARCHAR(255)                            NOT NULL,
    queue              VARCHAR(255)                            NOT NULL,
    status             VARCHAR(255)                            NOT NULL,
    content            TEXT                                    NOT NULL,
    fail_reason        VARCHAR(255),
    leased_by          INTEGER                                 NOT NULL,
    leased_until       TIMESTAMP WITH TIME ZONE,
    attempts_remaining INTEGER                                 NOT NULL,
    next_attempt_at    TIMESTAMP WITH TIME ZONE,
    created_at         TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_outbox_messages PRIMARY KEY (id)
);

CREATE TABLE remote_project_members
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id UUID                                    NOT NULL,
    user_id    UUID                                    NOT NULL,
    role       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_remote_project_members PRIMARY KEY (id)
);

CREATE TABLE storage_identifiers
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    storage_key VARCHAR(255)                            NOT NULL,
    used_in     INTEGER                                 NOT NULL,
    was_deleted BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_storage_identifiers PRIMARY KEY (id)
);

CREATE TABLE "task-run_artifact"
(
    output_id UUID NOT NULL,
    task_id   UUID NOT NULL,
    CONSTRAINT "pk_task-run_artifact" PRIMARY KEY (output_id, task_id)
);

CREATE TABLE task_runs
(
    id                  UUID                     NOT NULL,
    project_id          UUID                     NOT NULL,
    user_id             UUID                     NOT NULL,
    status              VARCHAR(255)             NOT NULL,
    jar_artifact_id     BIGINT,
    input_artifact_id   BIGINT,
    jar_jpa_id          BIGINT,
    input_jpa_id        BIGINT,
    execution_config_id UUID,
    task_type           SMALLINT                 NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    started_at          TIMESTAMP WITH TIME ZONE,
    finished_at         TIMESTAMP WITH TIME ZONE,
    done_at             TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_task_runs PRIMARY KEY (id)
);

ALTER TABLE inbox_messages
    ADD CONSTRAINT uc_inbox_messages_message UNIQUE (message_id);

ALTER TABLE input_artifacts
    ADD CONSTRAINT uc_input_artifacts_artifact UNIQUE (artifact_id);

ALTER TABLE jar_artifacts
    ADD CONSTRAINT uc_jar_artifacts_artifact UNIQUE (artifact_id);

ALTER TABLE outbox_messages
    ADD CONSTRAINT uc_outbox_messages_message UNIQUE (message_id);

ALTER TABLE storage_identifiers
    ADD CONSTRAINT uc_storage_identifiers_storage_key UNIQUE (storage_key);

ALTER TABLE artifacts
    ADD CONSTRAINT FK_ARTIFACTS_ON_STORAGE_IDENTIFIER FOREIGN KEY (storage_identifier_id) REFERENCES storage_identifiers (id) ON DELETE RESTRICT;

ALTER TABLE input_artifacts
    ADD CONSTRAINT FK_INPUT_ARTIFACTS_ON_ARTIFACT FOREIGN KEY (artifact_id) REFERENCES artifacts (id) ON DELETE CASCADE;

ALTER TABLE jar_artifacts
    ADD CONSTRAINT FK_JAR_ARTIFACTS_ON_ARTIFACT FOREIGN KEY (artifact_id) REFERENCES artifacts (id) ON DELETE CASCADE;

ALTER TABLE task_runs
    ADD CONSTRAINT FK_TASK_RUNS_ON_EXECUTION_CONFIG FOREIGN KEY (execution_config_id) REFERENCES execution_configs (id) ON DELETE SET NULL;

ALTER TABLE task_runs
    ADD CONSTRAINT FK_TASK_RUNS_ON_INPUT_ARTIFACT FOREIGN KEY (input_artifact_id) REFERENCES storage_identifiers (id) ON DELETE SET NULL;

ALTER TABLE task_runs
    ADD CONSTRAINT FK_TASK_RUNS_ON_INPUT_JPA FOREIGN KEY (input_jpa_id) REFERENCES input_artifacts (id) ON DELETE SET NULL;

ALTER TABLE task_runs
    ADD CONSTRAINT FK_TASK_RUNS_ON_JAR_ARTIFACT FOREIGN KEY (jar_artifact_id) REFERENCES storage_identifiers (id) ON DELETE SET NULL;

ALTER TABLE task_runs
    ADD CONSTRAINT FK_TASK_RUNS_ON_JAR_JPA FOREIGN KEY (jar_jpa_id) REFERENCES jar_artifacts (id) ON DELETE SET NULL;

ALTER TABLE "task-run_artifact"
    ADD CONSTRAINT fk_tasart_on_artifact_entity FOREIGN KEY (output_id) REFERENCES artifacts (id);

ALTER TABLE "task-run_artifact"
    ADD CONSTRAINT fk_tasart_on_task_run_entity FOREIGN KEY (task_id) REFERENCES task_runs (id);