CREATE TABLE remote_project_members
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    projectId UUID                                    NOT NULL,
    userId    UUID                                    NOT NULL,
    role      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_remote_project_members PRIMARY KEY (id)
);